### ISSUE TITLE
yaml config

### ISSUE THREAD

**Issue by Thomas55555** [stephan192/hochwasserportal#24]
I've got a warning, that the yaml config is beeing to removed, but I don't have a yaml config for this integration anymore. I also can't delete the integration, because there is still the repair to be solved.

**Comment by Dennis1000** [comment]
take a look at your main HA configuration.yaml, you will likely have added something like this before:

```
sensor:  
....
  - platform: hochwasserportal
    pegel: XY_123
    level: True
    stage: True
    flow: True
```
