### ISSUE TITLE
sensor naming

### ISSUE THREAD

**Issue by HerbyR56** [stephan192/hochwasserportal#3]
Hello,
I have installed it and added 2 sensors for the platform: 
- platform: hochwasserportal
  pegel: BY_24238501

After restarting I see no sensor with "hochwasserportal". What do I have to expect?

**Comment by Hohenloherin** [comment]
How did you install it? 
I managed to get it working after a cold restart (power off). Then I added a card in my dashboard. But the dashboard show only a straight line and does not show the changes. It did once, but I lost it again. 
FurhtermoreI am now struggling with the implementation of more than one 
![Pegelstand_Bühler_dashboard](https://user-images.githubusercontent.com/85617168/189717202-1259777e-c148-492d-9a67-335b08538536.png)
sensor in my sensor.yaml. If I add one more sensor in my sensor.yaml it says "duplicate key". Does someone know how to deal with this?

**Comment by stephan192** [comment]
I can't reproduce your problem.
My test setup (complete **configuration.yaml**) for multiple sensors:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    custom_components.hochwasserportal: debug

sensor:
  - platform: hochwasserportal
    pegel: BY_24238501
  - platform: hochwasserportal
    pegel: FRS_1464130
  - platform: hochwasserportal
    pegel: CZ_307039
  - platform: hochwasserportal
    pegel: NL_BMAAE
  - platform: hochwasserportal
    pegel: BY_16005701
```

After a restart the following sensor show up if you **don't** have configured your own lovelace dashboard(s).
![grafik](https://user-images.githubusercontent.com/62512016/189734196-259a4eda-0b63-4d3f-9d16-3f4e4a04be93.png)

If you look at the entity register you can find the sensors created by the hochwasserportal integration.
![grafik](https://user-images.githubusercontent.com/62512016/189735028-2ac09570-82fd-43ae-8c77-66edac91061b.png)
